# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-12-16 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200807_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='owner_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='\u5c5e\u4e3b\u7f16\u53f7'),
        ),
    ]
