# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2022-05-29 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20211216_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionhistory',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True, verbose_name='\u5bf9\u8c61ID'),
        ),
    ]
